name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      ver_name: "1.0.1"
    steps:
    
        
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - run: pip install requests
        
    - name: Init environment variable
      run: |
        python3 main_ubuntu_android.py
        echo "ver_name=$(python3 ajeossida/releng/frida_version.py)" >> $GITHUB_ENV


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18.19.1"

    - name: bulid frida
      run: |
        python3 main_ubuntu_android.py
        echo "ver_name=$(python3 ajeossida/releng/frida_version.py)" >> $GITHUB_ENV
      

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
          name: zygisk-gadget
          path: assets/
    
    - name: release
      uses: softprops/action-gh-release@v0.1.15
      with:
        name: ${{ env.ver_name }}
        tag_name: ${{ env.ver_name }}
        body_path: ${{ github.workspace }}/CHANGELOG.md
        draft: false
        prerelease: false
        files: ${{ github.workspace }}/assets/*.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
